language: node_js
node_js:
- '4'
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: jSEXUvthFeH1JnclS25GOV8WYeJYnBrtnG0+HAM+FqbrCwjHCj2PfijUFmd84rYLAP020IYTfV/3j0uKfLZfKlMmnkjM+a2F5yzFUNldoQlBfNzFvgyjWpUDlNt8KYClkR2o3NfCjt07+GehzS2DH/toRsPdkUGgLn6HP/drtPg=
  on:
    tags: true
    all_branches: true
